# Generated by Django 3.1 on 2023-02-10 07:25

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20230208_1814'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='variation',
            managers=[
                ('objets', django.db.models.manager.Manager()),
            ],
        ),
    ]
